# Generated by Django 5.1.4 on 2025-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='EN_ESPERA', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
